version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: SEERS
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro


  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: SEERS_backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=password_manager
      - AZURE_API_KEY=your_azure_api_key
      - AZURE_ENDPOINT=your_azure_endpoint
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data: